CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(64) NOT NULL,
  `password_hash` varchar(128) NOT NULL,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `username_lower` varchar(64) NOT NULL,
  `email_lower` varchar(100) NOT NULL,
  `avatar_url` text,
  `permission` int(10) unsigned NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `last_login_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `status` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_username` (`username`),
  UNIQUE KEY `user_email_lower_idx` (`email_lower`) USING BTREE,
  UNIQUE KEY `user_username_lower_idx` (`username_lower`) USING BTREE,
  UNIQUE KEY `uk_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `content` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user` int(11) NOT NULL DEFAULT '-1',
  `created_at` datetime NOT NULL,
  `modified_at` datetime NOT NULL,
  `title` varchar(233) DEFAULT NULL,
  `content` longtext NOT NULL,
  `order_level` int(11) NOT NULL DEFAULT '0',
  `type` int(11) NOT NULL,
  `status` int(11) NOT NULL DEFAULT '0',
  `view_password` varchar(233) DEFAULT NULL,
  `allow_comment` tinyint(1) NOT NULL DEFAULT '1',
  `allow_feed` tinyint(1) NOT NULL DEFAULT '1',
  `parent` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `content_user_idx` (`user`) USING BTREE,
  KEY `content_parent_idx` (`parent`) USING BTREE,
  KEY `content_order_level_idx` (`order_level`) USING BTREE,
  KEY `content_type_idx` (`type`) USING BTREE,
  KEY `content_status_idx` (`status`) USING BTREE,
  FULLTEXT KEY `content_content_idx` (`content`),
  FULLTEXT KEY `content_title_idx` (`title`),
  CONSTRAINT `content_content_fk` FOREIGN KEY (`parent`) REFERENCES `content` (`id`),
  CONSTRAINT `content_user_fk` FOREIGN KEY (`user`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
