image: docker:latest

services:
  -
    name: docker:dind

before_script:
  - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_TOKEN" $TIANHAI_REGISTRY

build-master:
  stage: build
  script:
    - docker build --pull -t "$TIANHAI_REGISTRY/$CI_PROJECT_PATH:dev-master" .
    - docker push "$TIANHAI_REGISTRY/$CI_PROJECT_PATH:dev-master"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$TIANHAI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG" .
    - docker push "$TIANHAI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG"
  except:
    - master

push-github:
  stage: build
  image: debian:stretch-slim
  variables:
    GIT_STRATEGY: clone
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$GITHUB_DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - git remote add github git@github.com:sohablog/sohablog.git
    - git fetch github
    - git push github --all
    - git push github --tags
  when: manual
