[package]
name = "soha-blog"
version = "0.1.0"
authors = ["Soha Jin"]
edition = "2018"

[dependencies]
diesel = { version = "1.3.3", features = [ "mysql", "r2d2" ] }
r2d2 = "0.8.3"
rocket = "0.4.0"
rocket_contrib = "0.4.0"
rocket_codegen = "0.4.0"
