[package]
name = "soha-blog"
version = "0.1.0"
authors = ["Soha Jin"]
edition = "2018"

[dependencies]
diesel = { version = "1.3.3", features = [ "mysql", "r2d2", "chrono" ] }
r2d2 = "0.8.3"
rocket = { version = "0.4.0", features = [ "private-cookies" ] }
rocket_contrib = { version = "0.4.0", features = [ "tera_templates" ] }
rocket_codegen = "0.4.0"
chrono = { version = "0.4.6", features = [ "serde" ] }
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.36"
bcrypt = "0.2.1"
tera = "0.11.20"

[patch.crates-io]
mysqlclient-sys = { git = 'https://github.com/sgrif/mysqlclient-sys' }
